# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Imperial College London
email: s.panditharatne21@imperial.ac.uk
full_name: Sanjeevani Panditharatne
github_organization: ImperialCollegeLondon
keywords: FINESSE
license: BSD
package_name: fir_simulation_wrapper
package_short_description: Code for simulating far-infrared measurements
template_profile: minimum
version: 0.1.0
